{% set version = "1.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cdft
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/CDFt_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/CDFt/CDFt_{{ version }}.tar.gz
  sha256: c1a88b31fb2ad2e174bdfcd1ab980ee5581920f3a555e5b4d5ea25b886535da5

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('CDFt')"           # [not win]
    - "\"%R%\" -e \"library('CDFt')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=CDFt
  license: GPL-2.0-or-later
  summary: This package proposes a statistical downscaling method for cumulative distribution functions (CDF), as well as the computation of the Cram\`er-von Mises statistics U, and the Kolmogorov-Smirnov statistics KS.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: CDFt
# Version: 1.0.1
# Date: 2009-25-03
# Title: Statistical downscaling through CDF-transform
# Author: Mathieu Vrac <mathieu.vrac@lsce.ipsl.fr> and Paul-Antoine Michelangeli <pam@climpact.com>
# Maintainer: Mathieu Vrac <mathieu.vrac@lsce.ipsl.fr>
# Depends: R (>= 1.8.0)
# Description: This package proposes a statistical downscaling method for cumulative distribution functions (CDF), as well as the computation of the Cram\`er-von Mises statistics U, and the Kolmogorov-Smirnov statistics KS.
# License: GPL (>= 2)
# Packaged: 2012-10-29 13:13:09 UTC; ripley
# Repository: CRAN
# Date/Publication: 2012-10-29 13:13:38
# NeedsCompilation: no
